# .github/workflows/lint-migrations.yml
name: Lint Migrations

on:
  # Run on pull_request and push to verify action works in both cases.
  #
  # When we run on push, we won't have a pull request to leave a comment on.
  pull_request:
  push:

jobs:
  lint_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          pattern: "*.sql"
