# .github/workflows/lint-migrations.yml
name: Lint Migrations

on:
  pull_request:
  push:

jobs:
  lint_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          pattern: "*.sql"
