# .github/workflows/lint-migrations.yml
name: Lint Migrations

on:
  # Run on pull_request and push to verify action works in both cases.
  #
  # When we run on push, we won't have a pull request to leave a comment on.
  pull_request:
  push:

permissions: {}

jobs:
  lint_migrations:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./
        with:
          pattern: "*.sql"
